const properties = [
  {
    id: 1,
    title: 'Warm Smart Apartment',
    price: 230000,
    address: '7394 Duis sit amet accumsan justo',
    bedrooms: 3,
    bathrooms: 2,
    pool: false,
    totalArea: 100,
    img: 'img/hotel/smart-hotel-1.jpg',
  },

  {
    id: 2,
    title: 'Grand Vip Villa',
    price: 450000,
    address: '4827 Suspendisse auctor laoreet placerat',
    bedrooms: 4,
    bathrooms: 3,
    pool: true,
    totalArea: 300,
    img: 'img/hotel/Grand-VIP-2.jpg',
  },
  {
    id: 3,
    title: 'Modern Smart Apartment',
    price: 150000,
    address: '3840 Nulla vel urna quis libero pharetra',
    bedrooms: 3,
    bathrooms: 2,
    pool: false,
    totalArea: 120,
    img: 'img/hotel/Moder-smar-3.jpg',
  },
  {
    id: 4,
    title: 'Spacious Calm House',
    price: 400000,
    address: '2948 Maecenas pellentesque lacus quis',
    bedrooms: 5,
    bathrooms: 3,
    pool: true,
    totalArea: 300,
    img: 'img/hotel/spacious-hotel-4.jpg',
  },
  {
    id: 9,
    title: 'Secure Smart House',
    price: 200000,
    address: 'Suspendisse auctor laoreet placerat',
    bedrooms: 4,
    bathrooms: 3,
    pool: true,
    totalArea: 250,
    img: 'img/hotel/Secure-smart-5.jpg',
  },
  {
    id: 10,
    title: 'Luxury Appartment',
    price: 120000,
    address: 'Maecenas pellentesque lacus quis erat',
    bedrooms: 2,
    bathrooms: 2,
    pool: false,
    totalArea: 130,
    img: 'img/hotel/Luxury-Apartmant-6.jpg',
  },
  {
    id: 11,
    title: 'Gorgeous Minimalist Villa',
    price: 300000,
    address: 'Nulla tellus nunc malesuada at scelerisque',
    bedrooms: 3,
    bathrooms: 2,
    pool: true,
    totalArea: 150,
    img: 'img/hotel/Gorgeous-hotel-7.jpg',
  },
  {
    id: 12,
    title: 'Cozy High‑Tech Villa',
    price: 500000,
    address: 'Sed vel maximus ante quis mattis neque',
    bedrooms: 5,
    bathrooms: 3,
    pool: true,
    totalArea: 400,
    img: 'img/hotel/Cozy-high-tech-8.jpg',
  },
  {
    id: 13,
    title: 'Grand House With Pool',
    price: 300000,
    address: '648 Weimann Radial, West Darrionside',
    bedrooms: 4,
    bathrooms: 2,
    pool: true,
    totalArea: 350,
    img: 'img/hotel/Grand-house-9.jpg',
  },
  {
    id: 14,
    title: 'Comfortable Apartment',
    price: 80000,
    address: '65940 Sonny Course, Lake Rachel',
    bedrooms: 2,
    bathrooms: 2,
    pool: false,
    totalArea: 80,
    img: 'img/hotel/comfortable-apartment-10.jpg',
  },
];
export default properties;
